### ISSUE TITLE
General cleanup ideas

### ISSUE THREAD

**Issue by nullchinchilla** [mel-project/melstf#19]
`themelio-stf` generally has a few problems:
- it's not clear how to use the crate to implement logic (e.g. block validation, constructing mock transactions for tests, etc)
- the internal implementation of some functionality is spaghetti (especially wrt melswap/melmint)
- performance is unexpectedly bad (we can't do more than a few hundred TPS in ideal conditions, which is *fine* for a blockchain, but bad for e.g. fuzzing or simulations)

fixing this requires:

- **Improving documentation**
  - Every type should come with a good description and a usage example
  - "Mysterious data structs" like `Transaction` should have every field properly docstringed
  - Include some full-fledged `/examples` with demo programs like:
     - revalidating the `history` folder produced by `themelio-node` (which is going to just be flat files containing blocks, which are trivial to parse)
     - a basic MelVM interpreter

- **Cleaning up the codebase**
   - Clean up types like `SmtMapping` (done-ish)
   - Improve the MelVM interface
      - `Covenant` and `Executor` is a pair of poorly thrown together types
      - Instead, I propose having just one type, `Executor`, that has:
         - A fallible constructor `Executor::load` that takes in a `&[u8]`, and an optional `ExecutionContext` (that itself has a constructor that takes in blockchain info), and attempts to interpret it as MelVM instructions
         - A single method `run(&self) -> RunResult`, where `RunResult` has cases like "ran to end with this truthy value", "ran to end with this falsy value", "died halfway through due to this problem", and has a helper method `.truthy()`
    - Greatly cleanup the whole Melswap/Melmint system
        - Make a wrapper type around the whole `pools` struct, with sensible, well-typed interfaces. This should be an "entry API", where there's a `Pool` type that encapsulates both the pool tokens and a `PoolState`
        - Melmint's exception to the transaction-balancing rule should be implemented more smartly. We should have a helper function that balances the balance for a particular `Denom`, and the `ERG` one would have a special case for minting transactions.

- **Performance**
   - fix `SmtMapping` inefficiencies (done)
   - set up a `criterion` benchmark suite
   - run a demo program under `perf` to see which part uses all the CPU time

**Comment by antidmg** [comment]
Running a simple loop for measuring TPS under `perf` showed that cloning an ever-growing `BTreeMap` of `Transaction`s was a bottleneck. Replacing that with a persistent [ordered map](https://docs.rs/imbl/2.0.0/imbl/ordmap/index.html) improves this a lot.

**Comment by nullchinchilla** [comment]
This is largely done now.
